version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g aws-cdk@latest
      - pip install --upgrade pip
      - echo "Deployment Type is $DEPLOYMENT_TYPE"
      
  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Deployment Type is $DEPLOYMENT_TYPE"
      - aws --version
      - cdk --version
      - bash -c 'if [ "$DEPLOYMENT_TYPE" = "pdf2html" ]; then echo "PDF-to-HTML pre-build"; docker --version; cd pdf2html && ls -la && aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com && cd ..; else echo "PDF-to-PDF pre-build"; pip install -r requirements.txt; cdk bootstrap || true; fi'
      
  build:
    commands:
      - echo "Build phase started on $(date)"
      - bash -c 'if [ "$DEPLOYMENT_TYPE" = "pdf2html" ]; then echo "Deploying PDF-to-HTML..."; cd pdf2html; if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then echo "Creating S3 bucket"; if [ "$REGION" = "us-east-1" ]; then aws s3api create-bucket --bucket $BUCKET_NAME --region $REGION; else aws s3api create-bucket --bucket $BUCKET_NAME --region $REGION --create-bucket-configuration LocationConstraint=$REGION; fi; aws s3api put-bucket-versioning --bucket $BUCKET_NAME --versioning-configuration Status=Enabled; aws s3api put-object --bucket $BUCKET_NAME --key uploads/; aws s3api put-object --bucket $BUCKET_NAME --key output/; aws s3api put-object --bucket $BUCKET_NAME --key remediated/; fi; REPO_NAME="pdf2html-lambda"; if ! aws ecr describe-repositories --repository-names $REPO_NAME --region $REGION 2>/dev/null; then aws ecr create-repository --repository-name $REPO_NAME --region $REGION; fi; REPO_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/pdf2html-lambda"; docker build --platform linux/amd64 --no-cache -t $REPO_URI:latest .; docker push $REPO_URI:latest; cd cdk; npm install; npx cdk bootstrap aws://$ACCOUNT_ID/$REGION; npx cdk deploy --app "node bin/app.js" --parameters BdaProjectArn=$BDA_PROJECT_ARN --parameters BucketName=$BUCKET_NAME --require-approval never; elif [ "$DEPLOYMENT_TYPE" = "pdf2pdf" ]; then echo "Deploying PDF-to-PDF..."; cdk deploy --all --require-approval never; else echo "Invalid DEPLOYMENT_TYPE"; exit 1; fi'
      
  post_build:
    commands:
      - echo "Post-build phase completed on $(date)"
      - bash -c 'if [ "$DEPLOYMENT_TYPE" = "pdf2html" ]; then echo "PDF-to-HTML deployment completed!"; echo "S3 Bucket: $BUCKET_NAME"; echo "BDA Project: $BDA_PROJECT_ARN"; else echo "PDF-to-PDF deployment completed!"; fi'
